FROM node:18-alpine
WORKDIR /app

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./


COPY apps/price-poller/package.json ./apps/price-poller/


RUN npm i -g pnpm
RUN pnpm install --frozen-lockfile


COPY apps/price-poller ./apps/price-poller


WORKDIR /app/apps/price-poller
RUN pnpm run build


CMD ["pnpm", "run", "start"]
