FROM node:18-alpine AS base


FROM base AS deps
WORKDIR /app


COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./


COPY apps/web/package.json ./apps/web/
COPY packages/ui/package.json ./packages/ui/
COPY packages/typescript-config/package.json ./packages/typescript-config/
COPY packages/eslint-config/package.json ./packages/eslint-config/


RUN npm i -g pnpm
RUN pnpm install --frozen-lockfile


FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/pnpm-lock.yaml ./pnpm-lock.yaml


COPY pnpm-workspace.yaml package.json ./
COPY turbo.json ./


COPY apps/web ./apps/web
COPY packages ./packages


RUN npm i -g pnpm


WORKDIR /app/apps/web
RUN pnpm run build


FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs


COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

USER nextjs

EXPOSE 3000

ENV PORT 3000


CMD ["node", "apps/web/server.js"]
