FROM node:18-alpine
WORKDIR /app


COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

COPY apps/engine/package.json ./apps/engine/
COPY packages/db/package.json ./packages/db/

RUN npm i -g pnpm
RUN pnpm install --frozen-lockfile

COPY apps/engine ./apps/engine
COPY packages/db ./packages/db


WORKDIR /app/apps/engine
CMD ["pnpm", "run", "dev"]